//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookAgency.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class category
    {
        public category()
        {
            this.books = new HashSet<book>();
        }
    
        public decimal id { get; set; }

        [Required()]
        [Display(Name = "Name")]
        public string category_name { get; set; }

        [Required()]
        [Display(Name = "Display Order")]
        public decimal display_order { get; set; }

        [Display(Name = "Url Keyword")]
        public string category_url_keyword { get; set; }

        [Display(Name = "Meta-Title")]
        public string meta_title { get; set; }

        [Display(Name = "Meta-Keyword")]
        public string meta_keyword { get; set; }

        [Display(Name = "Meta-Desc")]
        public string meta_desc { get; set; }
    
        public virtual ICollection<book> books { get; set; }
    }
}
