//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookAgency.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookAgencyEntities : DbContext
    {
        public BookAgencyEntities()
            : base("name=BookAgencyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admin> admins { get; set; }
        public DbSet<book> books { get; set; }
        public DbSet<cart> carts { get; set; }
        public DbSet<category> categories { get; set; }
        public DbSet<order> orders { get; set; }
        public DbSet<order_item> order_item { get; set; }
        public DbSet<page_mgmt> page_mgmt { get; set; }
        public DbSet<publisher> publishers { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<user_master> user_master { get; set; }
    }
}
