//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookAgency.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;
    public partial class OrderMaster
    {
        public OrderMaster()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public decimal order_id { get; set; }

        public decimal order_item_id { get; set; }

        [Required()]
        [Display(Name = "Order Date")]
        public System.DateTime order_date { get; set; }

        public System.Guid UserId { get; set; }

        [Required()]
        [Display(Name = "Status")]
        public string status { get; set; }

        [Required()]
        [Display(Name = "Total")]
        public decimal total { get; set; }

        [Display(Name = "Delivery Charge")]
        public Nullable<double> delivery_charge { get; set; }

        [Required()]
        [Display(Name = "Payment Status")]
        public string payment_status { get; set; }

        [Required()]
        [Display(Name = "Payment Amount")]
        public Nullable<decimal> payment_amount { get; set; }

        [Required()]
        [Display(Name = "Payment Currency")]
        public string payment_currency { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
