//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookAgency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public decimal order_id { get; set; }
        public decimal user_id { get; set; }
        public System.DateTime order_date { get; set; }
        public string cust_name { get; set; }
        public decimal total { get; set; }
        public double delivery_charge { get; set; }
        public string status { get; set; }
        public string payment_status { get; set; }
        public string status_detail { get; set; }
        public decimal payment_amount { get; set; }
        public string payment_currency { get; set; }
        public string authcode { get; set; }
        public string txn_id { get; set; }
        public string payer_email { get; set; }
        public string dname { get; set; }
        public string daddress { get; set; }
        public string demail { get; set; }
        public string dcity { get; set; }
        public string dpincode { get; set; }
        public string dstate { get; set; }
        public string dcountry { get; set; }
        public string dphone { get; set; }
        public string mobile { get; set; }
        public string admin_note { get; set; }
    }
}
