//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookAgency.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrderDetail
    {
        public decimal order_item_id { get; set; }
        public decimal order_id { get; set; }
        public decimal book_id { get; set; }

        [Required()]
        [Display(Name = "Quantity")]
        public decimal qty { get; set; }

        [Required()]
        [Display(Name = "Price")]
        public decimal price { get; set; }

        [Required()]
        [Display(Name = "Sub-Total")]
        public decimal subtotal { get; set; }
    
        public virtual OrderMaster OrderMaster { get; set; }
        public virtual book book { get; set; }
    }
}
