//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookAgency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class page_mgmt
    {
        public decimal page_id { get; set; }
        public string page_name { get; set; }
        public string page_title { get; set; }
        public string page_desc { get; set; }
        public string meta_title { get; set; }
        public string meta_keyword { get; set; }
        public string meta_desc { get; set; }
    }
}
