//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookAgency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class publisher
    {
        public publisher()
        {
            this.books = new HashSet<book>();
        }
    
        public decimal id { get; set; }
        public string publisher_name { get; set; }
        public decimal display_order { get; set; }
        public string publisher_url_keyword { get; set; }
        public string meta_title { get; set; }
        public string meta_keyword { get; set; }
        public string meta_desc { get; set; }
    
        public virtual ICollection<book> books { get; set; }
    }
}
