//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookAgency.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.carts = new HashSet<cart>();
            this.OrderMasters = new HashSet<OrderMaster>();
        }
    
        public System.Guid UserId { get; set; }

        [Required]
        [Display(Name = "Address")]
        public string address { get; set; }

        [Required]
        [Display(Name = "City")]
        public string city { get; set; }

        [Required]
        [Display(Name = "State")]
        public string state { get; set; }

        [Required]
        [Display(Name = "Country")]
        public string country { get; set; }

        [Required]
        [Display(Name = "Telephone")]
        public string telephone { get; set; }

        [Required]
        [Display(Name = "Mobile")]
        public string mobile { get; set; }

        [Required]
        [Display(Name = "Comments")]
        public string comments { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<cart> carts { get; set; }
        public virtual ICollection<OrderMaster> OrderMasters { get; set; }
    }
}
